server:
  port: 8084
spring:
  application:
    name: "CrediYaReportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: dev
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
security:
  jwt:
    secret: "${JWT_SECRET:my-super-secret-key-that-is-at-least-32-chars-long}"
    expiration: 3600
    json-exp-roles: "/roles"
entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/498606688180/reporte-solicitud-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8084"
aws:
  dynamodb:
    region: "us-east-2"